version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: todolist-conteiner
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5432"
    restart: always